#!/usr/bin/env python3
"""Compile Jinja2 templates into a Python dict for Vercel bundling.

Vercel's @vercel/python only traces .py files — .html templates are never
bundled.  This script embeds them as string literals in nse/_compiled.py,
which IS a .py file and WILL be imported.

Run before committing for Vercel:
    python3 compile_templates.py
"""
import os, glob

ROOT = os.path.dirname(os.path.abspath(__file__))
TPL_DIR = os.path.join(ROOT, "nse", "templates")
OUT = os.path.join(ROOT, "nse", "_compiled.py")


def compile():
    files = sorted(glob.glob(os.path.join(TPL_DIR, "**", "*.html"), recursive=True))
    templates = {}
    for path in files:
        key = os.path.relpath(path, TPL_DIR)
        with open(path, encoding="utf-8") as f:
            templates[key] = f.read()

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("# Auto-generated by compile_templates.py — do not edit.\n")
        f.write("# Run: python3 compile_templates.py\n\n")
        f.write("TEMPLATES = {\n")
        for key in sorted(templates):
            f.write(f"    {key!r}: {templates[key]!r},\n")
        f.write("}\n")

    print(f"Compiled {len(templates)} templates → nse/_compiled.py ({os.path.getsize(OUT):,} bytes)")


if __name__ == "__main__":
    compile()
